Fearture/reusable components 2
stackitgroup/interview-buddy-web pull request #12
Opened 2023-01-28 01:06 UTC by Naiby

2023-01-28 01:22 UTC, AlefrankM requested changes
Refactorize

2023-01-29 00:20 UTC, juliswer approved these changes
Good job! Please check my comment

2023-01-29 00:20 UTC, juliswer commented on src/components/common/Input.tsx
> +  let Icon
why are you using a let variable instead of a next state?

2023-01-30 13:50 UTC, AlefrankM commented on src/components/common/Input.tsx
> +  switch (type) {
We can use a dinamyc object instead of switch

2023-01-30 13:50 UTC, AlefrankM commented on src/components/common/Input.tsx
> +    | 'primary'
Can you create an enum or use an existing?

2023-01-30 13:51 UTC, AlefrankM commented on src/components/common/Input.tsx
> +    | 'text'
default is text

2023-01-30 13:51 UTC, AlefrankM commented on src/components/common/Input.tsx
> +  type:
Convert to Enum

2023-01-30 13:51 UTC, AlefrankM commented on src/components/common/Input.tsx
> +          type === 'file' ? 'file-input-ghost' : ''
You have to avoid this magic strings

2023-01-30 13:53 UTC, AlefrankM commented on src/layout/Header.tsx
> +      <Navbar background={background} />
What is this? A component just to call another component?

2023-01-30 13:54 UTC, AlefrankM commented on src/styles/tailwind.css
> +  .bg-bluelight-300 {
Please, you can use tailwind.config for these custom colors

2023-01-30 13:54 UTC, AlefrankM requested changes
Please

2023-01-30 20:28 UTC, AlefrankM submitted a review, later dismissed

2023-01-30 20:34 UTC, AlefrankM approved these changes

2023-01-30 20:38 UTC, merged