Feat/start session
stackitgroup/interview-buddy-web pull request #59
Opened 2023-02-08 22:08 UTC by angelstackit

2023-02-08 22:24 UTC, juliswer requested changes
Basically. Remove commented code.
On the other hand, amazing job man! Let's keep it up

2023-02-08 22:24 UTC, juliswer commented on src/components/InterviewDetail/InterviewDrawer.tsx
> +// import { updateCandidate } from '@/features/app/actions/candidate/updateCandidate/updateCandidate'
remove commented code

2023-02-08 22:24 UTC, juliswer commented on src/components/UpcomingInterviews/UpcomingInterviewItem.tsx
> +// import { getAvatarName } from '@/common/utils/get-avatar-name'
remove commented code

2023-02-08 22:24 UTC, juliswer commented on src/components/UpcomingInterviews/UpcomingInterviewItem.tsx
> +  // const avatarName = getAvatarName(
remove commented code

2023-02-08 22:24 UTC, juliswer commented on src/components/UpcomingInterviews/UpcomingInterviewItem.tsx
> +              {/* <span>{avatarName}</span> */}
remove commented code

2023-02-08 22:24 UTC, juliswer commented on src/components/common/SpinnerContainer.tsx
>          style={{
please avoid using the inLine styling. Use a css className instead or tailwind inline styling

2023-02-08 22:24 UTC, juliswer commented on src/pages/interview-session.tsx
> +// import { EmojisContainer } from '@/layout/EmojisContainer'
delete commented code (check the entire file)

2023-02-08 22:24 UTC, juliswer commented on src/pages/sessions/[interviewId].tsx
> +              // Next Link href just accepts strings?
I dont really undestand the todo.
Next Link href only accepts strings

2023-02-09 13:01 UTC, AlefrankM approved these changes

2023-02-09 13:02 UTC, merged